<?php
	define('ROOT_DIR','/Users/Timohee/Desktop/version_smarty/');
	//define('ROOT_DIR','/');
	define('SMARTY_DIR',ROOT_DIR.'smarty/');
	define('ROOT_TO_DIR','/');
	define('DOC_DIR','htdocs/');
	define('JS_DIR','js/');
	define('INCLUDES','includes/');
	define('STYLE','styles/');
	define('IMAGE','images/');
?>